name: Test
on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
      target_rev:
        required: true

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    name: "ChangeTogether test"
    steps:
      - name: Run Action
        uses: getsentry/hackweek-changetogether@main
        with:
          repo: ${{ inputs.repo }}
          target_rev: ${{ inputs.target_rev }}
